# Required to run project under the correct environment.
language: php

# Versions of PHP to run with.
php:
  - 5.5

# Commands to be run before environment runs.
before_script:
  - composer self-update
  - composer install

# Commands you want to run that will verify build.
script: phpunit

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always